
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
#    context-path: /pms_socket

spring:
  application:
    name: PmsSocket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///Salto
    #url: jdbc:mysql://localhost:3306
    username: root
    password: 123456



mybatis-plus:
  type-aliases-package: com.ljrh.pmssocket.entity
  mapper-locations: classpath:mapper/*.xml
  #是否开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: on



