

salto_server_url: http://192.168.0.200:8100

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
    context-path: /salto

spring:
  application:
    name: Ship
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///Salto
    #url: jdbc:mysql://localhost:3306
    username: root
    password: 123456


  mail:
    host: smtp.126.com
    username: jiabaokangsy@126.com
    password: syjbk126
    default-encoding: UTF-8

logging:
  level:
    org.springframework.web: DEBUG
    com.ship.server.dao: trace
    com.org.springframework.jdbc: trace



mybatis-plus:
  type-aliases-package: com.ljrh.shiserver.entity
  mapper-locations: classpath:mapper/*.xml
  #??????????????
  configuration:
    map-underscore-to-camel-case: on


